### ISSUE TITLE
Add support for weather data grid from NASA (including solar radiation)

### ISSUE THREAD

**Issue by jnsebgosselin** [cgq-qgc/pyhelp#34]
This Issue is blocked by Issue #33

**Comment by mraynauld** [comment]
Voici le lien pour le site NASA POWER : https://power.larc.nasa.gov/data-access-viewer/

De : Jean-Sébastien Gosselin [mailto:notifications@github.com]
Envoyé : 23 novembre 2018 10:22
À : cgq-qgc/pyhelp
Cc : Raynauld Melanie; Mention
Objet : Re: [cgq-qgc/pyhelp] Add support for solar radiation data from NASA (#34)


@mraynauld<https://github.com/mraynauld> Est-ce que tu pourrais me donner le lien des données stp pour les grilles de radiation solaire de la NASA. Ça va me permettre de mieux documenter le tout ici.

**Comment by jnsebgosselin** [comment]
@mraynauld Merci!

**Comment by FHuchet** [comment]
Je m'y mets mi-décembre à 💯 % ! D'autres projets sont en cours de mon côté.

**Comment by jnsebgosselin** [comment]
Here is a link to the definition of the various data available on the service: 
https://power.larc.nasa.gov/text/definitions.html

Here is a link to the API that can be used to download the data:
https://power.larc.nasa.gov/docs/v1/

Basically, we can get from them all the weather data related inputs that HELP needs, more specifically we can get daily wind, humidity, precipitation, air temperature and solar radiation.

**Comment by FHuchet** [comment]
I'm ready at 💯 % and fully motivated to start next week !

**Comment by jnsebgosselin** [comment]
https://github.com/ajwdewit/pcse/blob/master/pcse/db/nasapower.py
https://pcse.readthedocs.io/en/master/_modules/pcse/db/nasapower.html

**Comment by jnsebgosselin** [comment]
https://github.com/Open-Power-System-Data/weather_data

**Comment by jnsebgosselin** [comment]
https://github.com/brendanv/nasa-api

**Comment by jnsebgosselin** [comment]
It is up to the users to format their input data.

Supporting input data formatting from various external sources is too much maintenance work.
