### ISSUE TITLE
"Target environment permission" et modif' des attributs des graphes

### ISSUE THREAD

**Issue by FHuchet** [cgq-qgc/pyhelp#84]
Bonjour Jean-Sébastien,

En essayant de modifier les axes de mes graphes (via la commande CTRL + G), je me suis rendu compte que je ne pouvais pas le faire. En fait, je ne peux pas modifier le code sur le PC de modélisation de l'INRS (je voulais mettre 1974 à la place de 1980 pour les années - axe des X).
![image](https://user-images.githubusercontent.com/43864075/162061084-92b68fd1-7be3-42eb-b0d6-7ec29e639cd4.png)

J'ai donc relancé Anaconda et lors de l'update, l'accès vers le dossier semble refusé (pas la permission requise).
![image](https://user-images.githubusercontent.com/43864075/162060261-feacece9-fc24-4af1-99a0-2f9b2142e562.png)

Penses-tu que le fait de ne pas pouvoir modifier les attributs des graphes (tailles des polices, longueur des axes... etc) est lié à ce problème d'accès ?

J'ai en fait ouvert Spyder sur mon PC personnel et je peux faire la modification (j'ai pu modifier les années).
![image](https://user-images.githubusercontent.com/43864075/162061573-7ba89d66-a983-44b2-837e-cd339bfbe295.png)

Merci pour ta réponse,
Bonne journée.

**Comment by jnsebgosselin** [comment]
Oui. Ça veut dire que tu n'as pas l'autorisation de modifier les fichiers de pyhelp, car ces derniers sont installés à une endroit où tu n'as pas les droits d'écriture.

**Comment by jnsebgosselin** [comment]
Je pense que le plus simple, ce serait de copier les fichiers de pyhelp dans to dossier d'utilisateur où tu as les droits d'écriture et d'ajouter le "path" du dossier pyhelp dans Windows pour que Python utilise ce pyhelp au lieu de celui installé dans `C\ProgramData\Anaconda3\envs\PyHELP`.

Comme cela, tu pourrais modifier ta version de pyhelp sans danger. Idéalement, il faudrait documenter les besoins dans des issues et ajouter des options dans pyhelp pour ne pas avoir à modifier le code source.

**Comment by jnsebgosselin** [comment]
Mais bon, pour le moment dans `C\ProgramData\Anaconda3\envs\PyHELP\Lib\site-packages` tu devrais avoir un dossier nommé `pyhelp`. Copie le contenu de ce dossier à un endroit où tu as les droits d'écriture.

Ensuite dans Spyder, ajoute l'endroit où tu as copié le dossier pyhelp au "pythonpath" et redémarre spyder. En théorie, la version de pyhelp que tu as copié devrait alors être utilisée au lieu de celle installée dans `C\ProgramData\Anaconda3\envs\PyHELP`. Tu pourras alors modifier les fichiers à ta guise.

Essaie de faire un suivi de ce que tu fais et si possible crée de nouvelles issues pour documenter le tout.

![image](https://user-images.githubusercontent.com/10170372/162070811-186f982c-97e8-43c2-97d9-dce2a6cb417f.png)

**Comment by FHuchet** [comment]
Au final, ce qui a fonctionné c'est de me recréer un environnement PyHELP que j'ai nommé "PyHELP_" dans Anaconda avec un répertoire où j'avais le droit en écriture.

![image](https://user-images.githubusercontent.com/43864075/162082193-b407c559-4d39-4a36-b293-c5e58dfb5016.png)

Cela semble fonctionner. :)

**Comment by jnsebgosselin** [comment]
C'est une bonne solution ça. Plus simple que ce que j'ai proposé.

**Comment by FHuchet** [comment]
Oui. :)

**Comment by jnsebgosselin** [comment]
Excellent!
